#!/bin/bash
INTERVAL=2

while [ "$1" ]; do
	case "$1" in
		"-n") INTERVAL="$2"; shift 2;;
		*) break;
	esac
done

count=1
while true;
do
	printf "\033c"
	echo "#$count"
	"$@"
	sleep "$INTERVAL"
	count=$((count+1))
done
